project_name:
 webmetrics

dimensions:
  - country
  - domain
  - useragent
  - usertype
  - referrer

units:
  - pageviews
  - visitors

projections:
    country:
      - country
    domain:
      - domain
    country-domain-useragent-usertype:
      - country
      - domain
      - useragent
      - usertype
    country-useragent:
      - country
      - useragent
