dataset: apache

dimensions:
  - host
  - method
  - path
  - status
  - referrer
  - agent

projections:
  - path-method-status
  - agent-method--status
  - host-method-path-status-referrer-agent

units:
  - requests
  - bytes
