project_name: webmetrics

dimensions:
  - country
  - host
  - referer
  - useragent
  - usertype

units:
  pageviews:
    country:
      - country
    country-useragent-usertype:
      - country
      - useragent
      - usertype
  visitors:
    country-useragent:
      - country
      - useragent
