project_name:
 webmetrics

dimensions:
  - country
  - host
  - referrer
  - useragent
  - usertype

units:
  pageviews:
    country:
      - country
    domain:
      - domain
    country-domain-useragent:
      - country
      - domain
      - useragent
  visitors:
    country-useragent:
      - country
      - useragent
